version: "3"
services:
  api:
    image: crownai/fastapi
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME=${database_hostname}
      - DATABASE_PORT=${database_port}
      - DATABASE_PASSWORD=${database_password}
      - DATABASE_NAME=${database_name}
      - DATABASE_USERNAME=${database_username}
      - SECRET_KEY=${secret_key}
      - ALGORITHM=${algorithm}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${access_token_expire_minutes}

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
